### ISSUE TITLE
UTBK yang memusingkan

### ISSUE THREAD

**Issue by HaqiAchmad** [HaqiAchmad/Acaks#1]
Lagi pusing nih mikirin UTBK

**Comment by test-haqi** [comment]
Sama gw juga pusing mikirin UTBK

**Comment by HaqiAchmad** [comment]
> Sama gw juga pusing mikirin UTBK

Kimia sama matematika pusing banget anjir gw gk paham paham

**Comment by test-haqi** [comment]
> > Sama gw juga pusing mikirin UTBK
> 
> Kimia sama matematika pusing banget anjir gw gk paham paham

Semuanya susah mat, fis, kim sama bilogi tapi kalo tps gw jagonya wkwk

**Comment by HaqiAchmad** [comment]
Ya udah ya gw close aja
